version: "3.7"

services:
  gateway:
    extends:
      file: docker-compose.prod.yaml
      service: gateway
    build:
      target: debug
    volumes:
      - ./services/gateway:/usr/src/app:cached
      - /usr/src/app/node_modules
    ports:
      - 2000:2000
      - 2001:9229

  auth:
    extends:
      file: docker-compose.prod.yaml
      service: auth
    build:
      target: debug
    volumes:
      - ./services/auth:/usr/src/app:cached
      - /usr/src/app/node_modules
    ports:
      - 3001:9229

  user:
    extends:
      file: docker-compose.prod.yaml
      service: user
    build:
      target: debug
    volumes:
      - ./services/user:/usr/src/app:cached
      - /usr/src/app/node_modules
    ports:
      - 4001:9229

  postgres:
    extends:
      file: docker-compose.prod.yaml
      service: postgres
