apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: micro-services-sample
build:
  local:
    useBuildkit: true
  artifacts:
  - image: us.gcr.io/stream-k8s-micro-service/auth
    context: services/auth
    docker:
      dockerfile: Dockerfile
      target: production
  - image: us.gcr.io/stream-k8s-micro-service/gateway
    context: services/gateway
    docker:
      dockerfile: Dockerfile
      target: production
  - image: us.gcr.io/stream-k8s-micro-service/user
    context: services/user
    docker:
      dockerfile: Dockerfile
      target: production
deploy:
  helm:
    releases:
      - name: gateway
        chartPath: ./chart
        createNamespace: true
        imageStrategy:
          helm: {}
        artifactOverrides:
          image: us.gcr.io/stream-k8s-micro-service/gateway
        overrides:
          fullnameOverride: gateway
          service:
            port: 2000
          env:
            AUTH_SERVICE: auth
            AUTH_SERVICE_PORT: "2000"
            PORT: "2000"
            USER_SERVICE: user
            USER_SERVICE_PORT: "2000"
          livenessProbe:
            httpGet:
              port: 2000
              path: /status
          readinessProbe:
            httpGet:
              port: 2000
              path: /status
          autoscaling:
            enabled: true
            minReplicas: 1
            maxReplicas: 3
            targetCPUUtilizationPercentage: 50
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ingress:
            enabled: true
            className: nginx
            hosts:
              - host: gateway.34.125.206.209.nip.io
                paths:
                  - path: /
                    pathType: ImplementationSpecific

      - name: auth
        chartPath: ./chart
        createNamespace: true
        imageStrategy:
          helm: {}
        artifactOverrides:
          image: us.gcr.io/stream-k8s-micro-service/auth
        overrides:
          fullnameOverride: auth
          service:
            port: 2000
          env:
            PORT: "2000"
            USER_SERVICE: user
            USER_SERVICE_PORT: "2000"
          livenessProbe:
            tcpSocket:
              port: 2000
          readinessProbe:
            tcpSocket:
              port: 2000
          autoscaling:
            enabled: true
            minReplicas: 1
            maxReplicas: 3
            targetCPUUtilizationPercentage: 50
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

      - name: user
        chartPath: ./chart
        createNamespace: true
        imageStrategy:
          helm: {}
        artifactOverrides:
          image: us.gcr.io/stream-k8s-micro-service/user
        overrides:
          fullnameOverride: user
          service:
            port: 2000
          env:
            AUTH_SERVICE: auth
            AUTH_SERVICE_PORT: "2000"
            PORT: "2000"
            POSTGRES_URL: postgresql://user:password@postgres:5432/user
          livenessProbe:
            tcpSocket:
              port: 2000
          readinessProbe:
            tcpSocket:
              port: 2000
          autoscaling:
            enabled: true
            minReplicas: 1
            maxReplicas: 3
            targetCPUUtilizationPercentage: 50
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
