apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: micro-services-sample
build:
  local:
    useBuildkit: true
  artifacts:
  - image: micro-services-sample-auth
    context: services/auth
    docker:
      dockerfile: Dockerfile
      target: production
  - image: micro-services-sample-gateway
    context: services/gateway
    docker:
      dockerfile: Dockerfile
      target: production
  - image: micro-services-sample-user
    context: services/user
    docker:
      dockerfile: Dockerfile
      target: production
deploy:
  helm:
    releases:
      - name: gateway
        chartPath: ./chart
        createNamespace: true
        imageStrategy:
          helm: {}
        artifactOverrides:
          image: micro-services-sample-gateway
        overrides:
          fullnameOverride: gateway
          env:
            AUTH_SERVICE: auth
            AUTH_SERVICE_PORT: "2000"
            PORT: "2000"
            USER_SERVICE: user
            USER_SERVICE_PORT: "2000"
          livenessProbe:
            httpGet:
              port: 2000
              path: /status
          readinessProbe:
            httpGet:
              port: 2000
              path: /status
          autoscaling:
            enabled: true
            minReplicas: 1
            maxReplicas: 3
            targetCPUUtilizationPercentage: 50
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ingress:
            enabled: true
            className: nginx
            hosts:
              - host: gateway.127.0.0.1.nip.io
                paths:
                  - path: /
                    pathType: ImplementationSpecific
